apiVersion: v1
data:
  fluent.conf: |
    @include kubernetes.conf

    <match **>
       type elasticsearch
       log_level info
       include_tag_key true
       host "#{ENV['FLUENT_ELASTICSEARCH_HOST']}"
       port "#{ENV['FLUENT_ELASTICSEARCH_PORT']}"
       ssl_verify "#{ENV['FLUENT_ELASTICSEARCH_SSL_VERIFY']}"
       logstash_format true
       buffer_chunk_limit 2M
       buffer_queue_limit 32
       flush_interval 5s
       max_retry_wait 30
       disable_retry_limit
       num_threads 8
    </match>
  kubernetes.conf: |+
    <source>
      type tail
      path /var/log/containers/*.log
      pos_file /var/log/fluentd-containers.log.pos
      time_format %Y-%m-%dT%H:%M:%S.%NZ
      tag kubernetes.*
      format json
      read_from_head true
    </source>

    <filter kubernetes.**>
      type kubernetes_metadata
      merge_json_log true
    </filter>

    <match fluent.**>
      type null
    </match>


kind: ConfigMap
metadata:
  creationTimestamp: 2017-11-24T22:40:10Z
  name: fluentd-config
  namespace: logging
  resourceVersion: "368543"
  selfLink: /api/v1/namespaces/default/configmaps/fluentd-config
  uid: 6d8adbc4-d168-11e7-8c75-0a58ac1f0255
